Exercises: module, revealing module pattern and adapter.
blacklabel/highcharts-modules pull request #1
Opened 2022-08-30 13:18 UTC by pawelfus

2022-09-28 14:27 UTC, raf18seb requested changes
Nice!!!
Few questions:

2022-09-28 14:27 UTC, raf18seb commented on exercises/02-module-class/README.md
> +colorsGenerator.get(1); // returns blue
(confusing, not explained enough)
Maybe add small info that `get(1)` is the same as `get()`.

Or maybe there's a mistake here and it should be like this (see changed comments)
```js
colorsGenerator.get(1); // returns red
colorsGenerator.get(1); // returns red
```

2022-09-28 14:27 UTC, raf18seb commented on exercises/02-module-class/README.md
> +  - `get(n?: number): Array<string>`;
The return type should be `Array<string>` or `string`? It's inconsistent with this (a few lines above):
```js
colorsGenerator.get(2); // returns red and green
```

2022-09-28 14:27 UTC, raf18seb commented on README.md
> +Whenever some task is ready, on the separate branch prepare a PR with working demo, so the code might be reviewed by trainer.
Not a big deal, just for your information: we used to call ourselves "evaluators" instead of "trainers"

2022-09-28 14:27 UTC, raf18seb commented on exercises/01-revealing-module/README.md
> +In `color-generator.mjs` file create a module which will provide a color on demand, following the rules:
What do you mean by saying "create a module"?

When it comes to a file structure - do you mean
```js
const myFunction1 () =>{ ... };
const myFunction2 () =>{ ... };
const a = 5;

export default { myFun1, myFun2 };
```

or 

```js
const myModule = {
    myFunction1() { ... },
    myFunction2() { ... },
    a: 5
};

export default myModule;
```

?

2022-10-06 09:55 UTC, pawelfus commented on exercises/02-module-class/README.md
> +colorsGenerator.get(1); // returns blue
Nice catch!
`get(1)` and `get()` are equivalent, will add 👍

2022-10-06 09:57 UTC, pawelfus commented on exercises/02-module-class/README.md
> +  - `get(n?: number): Array<string>`;
It should be `Array<string>`. It's red **and** green, so given the requirements, the example above should return: `[ red, green ]`

2022-10-06 10:03 UTC, pawelfus commented on exercises/01-revealing-module/README.md
> +a) Public methods:
You need to read lesson `README.md` first. There's a link to the Revealing module pattern which shows an example with public/private methods/variables

2022-10-06 10:05 UTC, pawelfus commented on exercises/02-module-class/README.md
> +  - `get(n?: number): Array<string>`;
I can change comments from `returns red` to `returns ['red']` and `returns red and green` to `returns ['red', 'green']`

2022-10-06 10:08 UTC, pawelfus commented on exercises/01-revealing-module/README.md
> +In `color-generator.mjs` file create a module which will provide a color on demand, following the rules:
The exercise name is `revealing module`, so the module should be like described in README: https://www.patterns.dev/posts/classic-design-patterns/#revealingmodulepatternjavascript 

Improved the description 👍

2022-10-06 10:13 UTC, pawelfus commented on exercises/02-module-class/README.md
> +colorsGenerator.get(1); // returns blue
Added

2022-10-06 10:17 UTC, raf18seb commented on exercises/02-module-class/README.md
> +  - `get(n?: number): Array<string>`;
Yes, that would be perfect

2022-10-06 10:41 UTC, raf18seb commented on exercises/02-module-class/README.md
> +  - `get(n?: number): Array<string>`;
Done

2022-10-06 10:45 UTC, raf18seb commented on exercises/01-revealing-module/README.md
> +a) Public methods:
Ok, I misunderstood then. Now I get it, thanks!

2022-10-06 10:45 UTC, raf18seb approved these changes
No more insights, nice work and approved!

2022-10-07 09:32 UTC, merged